# Generated by Django 3.0.14 on 2022-07-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company1',
            new_name='Company',
        ),
    ]
