# Generated by Django 4.1 on 2022-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_company_name_alter_company_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
